### ISSUE TITLE
Some entity node collapse/expand glyphs show empty

### ISSUE THREAD

**Issue by arawinters** [senzing-garage/sdk-components-ng#312]
**Describe the bug**
When a primary entity node has all children visible an empty collapse bubble shows.

the entity nodes classes are: `graph-node-rel-primary sz-graph-node sz-graph-primary-node sz-graph-all-related-visible`

and the count node glyph markup is as follows:
```html
<text text-anchor="middle" dy=".14rem" x="12" y="-10" font-weight="bold" font-size=".45rem" class="sz-graph-icon-edge-glyph sz-graph-icon-edge-glyph-collapsed">0</text>
```
and the minus sign glyph( the one that SHOULD be showing) is:
```html
<path x="12" y="-10" height="24" width="24" d="M0 10h24v4h-24z" class="sz-graph-icon-edge-glyph sz-graph-icon-edge-glyph-expanded" transform="translate(8.5,-13.75) scale(.3)" style="fill: rgb(255, 255, 255);"></path>
```
and the style rule that's hiding the glphy is:
```css
body .sz-graph-primary-node.sz-graph-all-related-visible .sz-graph-icon-edge-glyph-expanded, body .sz-graph-primary-node.sz-graph-all-related-visible .sz-graph-icon-expand {
    display: none;
}
```

which would indicate that the `.sz-graph-all-related-visible .sz-graph-icon-edge-glyph-expanded` class that 's being applied to the entity node is incorrect since that would mean that **_if all of the entities nodes are visible hide the collapse glyph when the node is a primary node?_**

**Expected behavior**
I'd expect the bubble to not be there at all OR the bubble to show the `-` glyph.

**Screenshots**
![image](https://user-images.githubusercontent.com/13721038/174355014-7c6cb7c8-7e74-49f6-bff6-e81e00e4753e.png)

**Additional context**
This only seems to happen for the primary node(s) (the ones that are passed to the graph as seed entities)
